const LIVEKIT_API_URL = process.env.LIVEKIT_API_URL;
const LIVEKIT_API_KEY = process.env.LIVEKIT_API_KEY;
const LIVEKIT_API_SECRET = process.env.LIVEKIT_API_SECRET;
const LIVEKIT_WS = process.env.NEXT_PUBLIC_LIVEKIT_WS_URL;

export { LIVEKIT_API_URL, LIVEKIT_API_KEY, LIVEKIT_API_SECRET, LIVEKIT_WS };
